name: CreativeElytra
version: 1.04
api-version: 1.13
main: me.F_o_F_1092.CreativeElytra.Main
author: F_o_F_1092
commands:
  CreativeElytra:
    description: none
    usage: /CreativeElytra
    aliases: [ce]